name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: php-fpm-queue-monitor-linux-amd64
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            name: php-fpm-queue-monitor-linux-arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build binary
      uses: houseabsolute/actions-rust-cross@v1
      with:
          command: build
          target: ${{ matrix.target }}
          args: "--release"
          rust-cache-parameters: |
            {"cache-all-crates": true, "cache-on-failure": true}
    - run: |
        mkdir -p target/release
        cp target/${{ matrix.target }}/release/php-fpm-queue-monitor target/release/php-fpm-queue-monitor

    - name: Generate RPM
      run: cargo install cargo-generate-rpm

    - run: cargo generate-rpm

    - name: Prepare artifact
      run: |
        ls target
        ls target/generate-rpm
        mkdir -p artifacts
        cp target/${{ matrix.target }}/release/php-fpm-queue-monitor artifacts/${{ matrix.name }}
        cp target/generate-rpm/*.rpm artifacts/${{ matrix.name }}.rpm

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}
        path: artifacts/${{ matrix.name }}*

  upload-to-release:
    name: Upload to Release
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Upload artifacts to release
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/*/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
